### PR TITLE
chore: Replacing KubernetesServicePatch with ops.set_ports

### PR DESCRIPTION
**Pull request by Gmerold**
# Description

This PR replaces `KubernetesServicePatch` with `ops.set_ports` for setting the ports exposed by the workload.
It's worth noting, that with `ops.set_ports`, we can't remove the default port `65535` created by Juju and also we're not able to set custom name for the port. `ops` will automatically set the name of the port to `juju-{PORT_NUMBER}-tcp`

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have bumped the version of the library

### CODE REVIEW

**Comment by jnsgruk** [comment]
The placeholder port thing was fixed a couple of days ago so should land in the next release :) https://github.com/juju/juju/pull/16617

**Comment by Gmerold** [comment]
> The placeholder port thing was fixed a couple of days ago so should land in the next release :) [juju/juju#16617](https://github.com/juju/juju/pull/16617)

It's been 4 minutes since I created this PR... :O How...? :rofl:

**Comment by gruyaume** [comment]
@Gmerold Have we tested this properly? I'm somewhat worried about making such changes right before promoting our SD-Core charms to beta.

**Comment by Gmerold** [comment]
@gruyaume Just finished the test and it seems just fine: bundle with updated charm deploys without any issues, simulation with `gnbsim`  works as expected.

**Review by ghislainbourgeois — APPROVED** [review]

**Pull request merged**
